### ISSUE TITLE
Use same prompt for all images not working.

### ISSUE THREAD

**Issue by VRArt1** [Inzaniak/sd-webui-ranbooru#6] opened 2023-10-14 12:02 UTC
I've noticed that all the images generated while using this shares the same prompt even though I have the toggle for 'Use same prompts for all images' off. I'm guessing maybe somewhere in the script where it checks if that's on or if is borked and it's not doing the right thing for if it's unchecked.

**Comment by Inzaniak** [comment] 2023-10-14 13:11
Hi! There was a user with the same issue as you:
#2 
It could be two things:
- An extension is doing something funny with the prompt
- You have accidentally inserted the tags in the "Post ID" field
Let me know if that's your case.

**Comment by VRArt1** [comment] 2023-10-14 13:46
I haven't touched the post id section so maybe an extension then?

I have the following extensions:

```
sd-webui-e621-prompt
sd-webui-enable-checker
sd-webui-ranbooru
sd-webui-sendtonegative
stable-diffusion-webui-images-browser
stable-diffusion-webui-pixelization
stable-diffusion-webui-rembg
Styles-Editor
a1111-sd-webui-tagcomplete
Config-Presets
sd-dynamic-prompts
sd-webui-ar
sd-webui-controlnet
```

Just got this error so it seems it may be related to sendtonegative:
```
Using e621
https://e621.net/posts.json?limit=100&page=43&tags=-animated
No file_url found, using random pic
No file_url found, using random pic
No file_url found, using random pic
No file_url found, using random pic
Processing Multiple Prompts
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 4 images in a total of 4 batches.
*** Error running process: C:\Users\vrart\Desktop\AI\stable-diffusion-webui\extensions\sd-webui-sendtonegative\scripts\extension.py
    Traceback (most recent call last):
      File "C:\Users\vrart\Desktop\AI\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\Users\vrart\Desktop\AI\stable-diffusion-webui\extensions\sd-webui-sendtonegative\scripts\extension.py", line 41, in process
        for i in range(len(p.all_hr_prompts)):  # pylint: disable=consider-using-enumerate
    TypeError: object of type 'NoneType' has no len()
```

After removing sendtonegative I can confirm that wasn't it since it was still producing the issue of using the same prompt now just with the following text output:
```
Using e621
https://e621.net/posts.json?limit=100&page=54&tags=-animated
No file_url found, using random pic
No file_url found, using random pic
No file_url found, using random pic
No file_url found, using random pic
Processing Multiple Prompts
```

**Comment by Inzaniak** [comment] 2023-10-14 19:36
The other use with the same issue mentioned it was "sd-dynamic-prompts" that caused the problem. Try disabling it and see if that's the case.

**Comment by Inzaniak** [comment] 2023-10-18 08:31
Closing this as it is a duplicate of:
https://github.com/Inzaniak/sd-webui-ranbooru/issues/2

**Closed by Inzaniak** 2023-10-18 08:31 UTC
Labels: bug
